language: objective-c

osx_image: xcode10.1

cache:
  directories:
  - $HOME/.cocoapods/repos/master/

script:
  - rvm use system
  - sudo gem install cocoapods -v '1.5.3'
  - if [ -d "$HOME/.cocoapods/repos/master/" ]; then pod repo update; else rm -rf ~/.cocoapods/repos/master && pod setup; fi
