language: objective-c

osx_image: xcode10.1

cache:
  directories:
  - $HOME/.cocoapods/repos/master/
  
before_install:
  - rvm use system
  - sudo gem install cocoapods -v '1.5.3'
  - if [ -d "~/.cocoapods/repos/master/" ]; then pod repo update; else pod setup; fi
