language: android
dist: trusty
jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-27
    - android-28

before_install:
  - nvm --version
  - nvm install 'lts/*'
  - node --version
  - npm --version
  - touch ~/.android/repositories.cfg
  - yes | sdkmanager "platforms;android-27"
  - yes | sdkmanager "platforms;android-28"

install:
  - npm install
  - sdkmanager --list

script:
  - echo "Understanding Travis builds..."
